@url=http://localhost:5029

GET {{url}}/weatherforecast

###
GET {{url}}/websites

###
GET {{url}}/widgets

###
GET {{url}}/widgets?color=Blue

###
POST {{url}}/widgets
Content-Type: application/json

{
  "weight": 442,
  "color": "Blue"
}

###
POST {{url}}/widgets
Content-Type: application/json

{
  "weight": 23,
  "color": "Red"
}

### 
PATCH {{url}}/widgets/27921bc6-f451-4a7f-befc-a6d999c54ffd
Content-Type: application/json

{
  "weight": 333
}

###
POST {{url}}/widgets/dbc20c0c-8ac7-439c-83fc-29bab02bc2b7/analyze

###
DELETE {{url}}/widgets/dbc20c0c-8ac7-439c-83fc-29bab02bc2b7
