@url=http://localhost:5029

GET {{url}}/weatherforecast

###
GET {{url}}/websites

###
GET {{url}}/widgets

###
GET {{url}}/widgets?color=Blue

###
POST {{url}}/widgets
Content-Type: application/json

{
  "weight": 442,
  "color": "Blue"
}

###
POST {{url}}/widgets
Content-Type: application/json

{
  "weight": 23,
  "color": "Red"
}

### 
PATCH {{url}}/widgets/27921bc6-f451-4a7f-befc-a6d999c54ffd
Content-Type: application/json

{
  "weight": 333
}

###
POST {{url}}/widgets/31b16533-2695-4197-bc84-e9b72a2a9060/analyze

###
DELETE {{url}}/widgets/31b16533-2695-4197-bc84-e9b72a2a9060
